
[env]
TERM = "xterm-256color"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"


[scrolling]
history = 15000
multiplier = 3

[window]
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 5
y = 0

[general]
import = ["~/.config/alacritty/theme_dark.toml", "~/.config/alacritty/keybinds.toml"]
